### ISSUE TITLE
Email login

### ISSUE THREAD

**Issue by krillin666** [nkalupahana/baseline#247]
Very nice that this app supports a web version. Unfortunately, there's no way to login without using proprietary services. 
Could you add a normal email login ?

**Comment by nkalupahana** [comment]
Hi! Unfortunately, email login isn't currently supported because of the way baseline encrypts user data. To protect your journal entries, we encrypt user data with unique keys that are held by Google/Apple per user, thus stopping us or anyone who gains access to our database from reading anyone's entries. 

We could add an offline key storage option for email/password login, but because there isn't significant demand for this feature at the time, it isn't on our current roadmap. If you'd like to help create this feature, though, we welcome PRs!
